import { Group, Play } from "./src/api/animate";
import { defaultSkybox } from "./src/util/skybox.util";
import { WebaniCanvas } from "./src/rendering/webani-canvas.class";
import { Cube } from "./src/api/components/cube.component";
import { Colors } from "./src/lighting/colors";
import { SphereMesh } from "./src/api/components/models/models";
import { Sphere } from "./src/api/components/sphere.component";
import { Text } from "./src/api/components/text.component";
import { Square, SquareComponent } from "./src/api/components/square.component";
import { WebaniMaterial } from "./src/lighting/webani-material.class";

WebaniCanvas.defaultCanvas.setSkybox(defaultSkybox);

const text = Text("Hello Aniket.", [0, 0], 700, Colors.BLACK);
text.Wait(3000);
text.TransformInto(Text("I stayed up.", [0, 0], 700, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Text("As you can see...", [0, 0], 500, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Text("It was worth it.", [0, 0], 600, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Text("Here's a demo:", [0, 0], 600, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Square([0, 0], 1500, Colors.BLACK));
text.Rotate([0, 45, 0], 5000);
text.Wait(500);
text.TransformInto(Text("Let's change the surface roughness.", [0, 0], 400, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Square([0, 0], 1500, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Square([0, 0], 1500, Colors.BLACK, 1, new WebaniMaterial(Colors.BLACK, 0, 0.3, 1)), 2000);
text.Rotate([0, 360, 0], 20000);
text.TransformInto(Square([0, 0], 1500, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Text("Don't worry.", [0, 0], 400, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Text("It's still a math animation library.", [0, 0], 400, Colors.BLACK));
text.Wait(2000);
text.TransformInto(Text("$\\int_a^b f(x) \\, dx = F(b) - F(a)$", [0, 0], 400, Colors.BLACK));
text.Wait(2000);
text.Rotate([360, 360, 0], 20000);
Play(text);